################################################################################
# Set the power analysis mode
################################################################################

set power_enable_analysis   true
set power_analysis_mode     time_based

################################################################################
# Link design, load constraints and activity file
################################################################################

set search_path     "lib ."
set link_library    "* core_typ.db"
read_verilog        aes_encrypt_unit.vg
current_design      aes_encrypt_unit
link

################################################################################
# Run timing analysis, read in constraints and switching activity file
################################################################################

update_timing
read_sdc lib/aes_encrypt_unit.sdc
read_vcd -strip_path testbench/dut dump.vcd

################################################################################
# Perform power analysis
################################################################################

set_power_analysis_options -waveform_format out                 \
                           -waveform_output power_waveform      \
                           -waveform_interval .01               \
                           -include top

check_power
update_power
report_power
report_power -hierarchy
quit

